version: '3.9'

services:
  qxj-server:
    image: qxjourney-server
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_SERVER_PORT=5345
    ports:
      - "${EXTERNAL_SERVER_PORT}:5345"